### PR TITLE
Add more comment handling

### PR DESCRIPTION
**Pull request by Booksbaum**
Currently only top level summary & `@param` on some types are supported.  
This greatly expands the supported Types, Tags & and converts links and code in text into xml. 

Supported Tags: (not all are official JSDoc Tags, but quite often used in Definitely Typed repo)
* top level text `/** description */` -> `<summary>` (was already handled)
* `@summary` -> `<summary>`
* `@description`/`@desc` -> `<summary>`
* `@param` -> `<param>` (was already handled)
* `@returns`/`@return` -> `<return>`
* `@example` -> `<example>`
* `@remarks`/`@remark`/`@note` -> `<remarks>`
* `@typeparam`/`@tparam` -> `<typeparam>`
* `@see` -> `<seealso>` (not yet processed)
* `@throws`/`@throw`/`@exception` -> `<exception>`
* Not officially supported xml tags, but are converted anyway
  * `@version` -> `<version>`
  * `@default`/`@defaultValue` -> `<default>`
*  `@deprecated` -> `Obsolete` Attribute

Supported JSDoc/Markdown:
* links (`{@link ...}`, `[title](target)`)
  * simple differentiation between href & cref by looking for `://`
* code (inline & multi line)

Parsing/Replacement is done via simple Regexes.  
These regexes use named capture groups. Which has some shortcomings:
* Not supported by Fable: https://github.com/fable-compiler/Fable/issues/1820 (-> I'm using some hacks...)
* Not supported in older browser or node versions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility  
  Shouldn't be an issue for a dev tool

Still: way easier to use than via group index or use something else.

### CODE REVIEW

**Comment by Booksbaum** [comment]
> nodejs.install v14.14.0 [Approved]
nodejs.install package files install completed. Performing other installation steps.
Installing 64 bit version
Installing nodejs.install...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\nodejs.install_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\nodejs.install\tools\node-v14.14.0-x64.msi" /quiet ADDLOCAL=ALL REMOVE=NodeEtwSupport ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\nodejs.install_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The install of nodejs.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\nodejs.install\tools\chocolateyInstall.ps1'.
 See log for details.

hm???

**Comment by alfonsogarciacaro** [comment]
This is great @Booksbaum! Thanks a lot as always! @humhei Do you want to review or can we merge as is? BTW, maybe it's a good idea to make @Booksbaum collaborator of the repo so PRs can be merged faster if needed when there are no reviewers available?

**Comment by humhei** [comment]
> maybe it's a good idea to make @Booksbaum collaborator of the repo so PRs can be merged faster if needed when there are no reviewers available?

Totally agree.

**Comment by alfonsogarciacaro** [comment]
Great! Then let's merge the PR. I've also sent an invitation to @Booksbaum to join ts2fable. Welcome to the team!

**Comment by Booksbaum** [comment]
Thanks :)

**Pull request merged**
