### PR TITLE
WIP rewrite ts2fable in Fable

### PR DESCRIPTION
**Pull request by ctaggart**
I started rewriting ts2fable using Fable. I am using the TypeScript API that I imported using the TypeScript based ts2fable after I hacked it a bit. My goal is to be able to import the API from my new version. That is probably a couple days of work.

It is early work-in-progress, but I wanted to let people know.

TODO:
- [x] Is webpack even needed for this Node app? (No, switched to fable-splitter)
- [x] map method signatures
- [x] map property signatures
- [x] merge same modules
- [x] merge same interfaces
- [x] map function signatures
- [x] add functions to Globals type
- [x] add generic tic in interface
- [x] map class declarations
- [x] map arrays
- [x] map enums with string values
- [x] map enum with int and undefined
- [x] ParamArray
- [x] Date to DateTime
- [x] map index signatures
- [x] map [String Literal Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html)
- [x] map global variables
- [ ] map global variables [to importAll](https://github.com/fable-compiler/Fable/issues/1200#issuecomment-339335379)
- [ ] map export statements
- [ ] map `this` references, left as `obj`
- [ ] map CallSignature
- [ ] map ConstructSignature
- [ ] erase unions with duplicate types (from enum types)

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
This is awesome @ctaggart, thanks a lot for this! I was a bit reluctant to write ts2fable in Fable because I thought it was easier to handle TypeScript AST using the same language, but on the other hand it's also a great case of dogfooding for Fable and if you're up to the task, I'll help you with whatever you need! 💪 

I've tried several times to rewrite ts2fable using [the type checker](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker) and indeed I have a [very, very early prototype](https://github.com/fable-compiler/ts2fable/tree/type-checker) using [ts-simple-ast](https://github.com/dsherret/ts-simple-ast), but always Fable bugs distract from keeping working on it. So I really appreciate your help and I'm completely up to join forces and helping you make this PR go through :clap: :clap:

About Webpack, indeed it's not necessary. You can use [fable-splitter](https://www.npmjs.com/package/fable-splitter) to just compile files without bundling. Here you can see an example on how to [automatically run the app](https://github.com/fable-compiler/fable-compiler.github.io/blob/44ae5654e4ce8a3f7ba4f1698ce6f44e66ff7b43/splitter.config.js#L33) after every watch compilation.

**Comment by ctaggart** [comment]
Thanks @alfonsogarciacaro, I just switched to fable-splitter and I really speeds up development round trip with `dotnet fable npm-start`.

**Comment by ctaggart** [comment]
Just took a look  at making `Globals` an interface, but it doesn't work with generics.

``` fs
    and Globals2 =
        abstract version: string with get
        abstract createNode: kind: SyntaxKind * ?pos: int * ?``end``: int -> Node
        abstract createIdentifier: text: string -> Identifier
        abstract createParameter: decorators: ReadonlyArray<Decorator> option * modifiers: ReadonlyArray<Modifier> option * dotDotDotToken: DotDotDotToken option * name: U2<string * BindingName> * ?questionToken: QuestionToken * ?``type``: TypeNode * ?initializer: Expression -> ParameterDeclaration
        abstract createBinary: left: Expression * operator: SyntaxKind * right: Expression -> BinaryExpression
        abstract createBlock: statements: Statement array * ?multiLine: bool -> Block
        abstract createCall: expression: Expression * typeArguments: TypeNode array option * argumentsArray: Expression array -> CallExpression
        abstract createIf: expression: Expression * thenStatement: Statement * ?elseStatement: Statement -> IfStatement
        abstract createReturn: ?expression: Expression -> ReturnStatement
        abstract createSourceFile: fileName: string * sourceText: string * languageVersion: ScriptTarget * ?setParentNodes: bool * ?scriptKind: ScriptKind -> SourceFile
        abstract createPrinter: ?printerOptions: PrinterOptions * ?handlers: PrintHandlers -> Printer
        abstract createLiteral: value: int -> NumericLiteral
        abstract createFunctionDeclaration: decorators: Decorator array option * modifiers: Modifier array option * asteriskToken: AsteriskToken option * name: U2<string * Identifier> option * typeParameters: TypeParameterDeclaration array option * parameters: ParameterDeclaration array * ``type``: TypeNode option * body: Block option -> FunctionDeclaration
        abstract createToken<'TKind>: token: SyntaxKind -> Token<'TKind>
        abstract createKeywordTypeNode: kind: SyntaxKind -> KeywordTypeNode
        abstract forEachChild<'T>: node: Node * ?cbNode: Func<Node * 'T option> * ?cbNodeArray: Func<Node array * 'T option> -> 'T option -> 'T option
        abstract isLiteralExpression: node: Node -> bool
```

image

May be I misunderstood one of the bullet points in #1. I'm going to leave it a class.

**Comment by ctaggart** [comment]
@alfonsogarciacaro, how do I map string enums like this this one from typescript.d.ts?

``` ts
    enum ScriptElementKindModifier {
        none = "",
        publicMemberModifier = "public",
        privateMemberModifier = "private",
        protectedMemberModifier = "protected",
        exportedModifier = "export",
        ambientModifier = "declare",
        staticModifier = "static",
        abstractModifier = "abstract",
    }
```

**Comment by ctaggart** [comment]
And then how do I map this enum from the same file?
``` ts
    and Ternary =
        | False = 0
        | Maybe = 1
        | True = undefined
```

**Comment by ctaggart** [comment]
StringEnum attribute is documented. http://fable.io/docs/interacting.html

``` fs
[<StringEnum>]
type MyStrings =
    | Vertical
    | [<CompiledName("Horizontal")>] Horizontal
```

Implementing now. Still not sure what to do about `Ternary`.

**Comment by alfonsogarciacaro** [comment]
@ctaggart Hmm, you can use Enums in Fable, but in this case `| True = undefined` won't work. I guess we could add a new attribute (something like `EnumValue`):

```fsharp
type EnumValue(value: obj) =
    inherit Attribute()

type Ternary =
    | [<EnumValue(0)>] False
    | [<EnumValue(1)>] Maybe
    | [<EnumValue(null)>] True
```

So in this case `Ternary` will always be replaced by the `EnumValue`. .NET attributes only accept literals as constructor arguments but probably this is enough, what do you think?

**Comment by alfonsogarciacaro** [comment]
Another less verbose option could be:

```fsharp
type DynamicEnum(values: obj[]) =
    inherit Attribute()

[<DynamicEnum([|0; 1; null|])>]
type Ternary =
    | False
    | Maybe
    | True
```

**Comment by ctaggart** [comment]
Bootstrapped! The `typescript.fs` is now the being generated by the new ts2fable which uses it.

**Comment by ctaggart** [comment]
This is ready to be tested with more inputs. It can produce bindings for TypeScript and [for izitoast](https://github.com/fable-compiler/Fable/issues/1200#issuecomment-339305141).  There are a couple of issues to work through for electron, react, and node.

```
cd src
dotnet fable npm-build
node ..\dist\ts2fable.js ..\node_modules\izitoast\dist\izitoast\izitoast.d.ts bin\izitoast.fs
```

For quick roudtrip, you can run `dotnet fable npm-start` and adjust this section at the bottom of the `ts2fable.fs`.
``` fs
if argv |> List.exists (fun s -> s = "splitter.config.js") then // run from build
    // printFile "node_modules/izitoast/dist/izitoast/izitoast.d.ts"
    writeFile "node_modules/izitoast/dist/izitoast/izitoast.d.ts" "src/bin/izitoast.fs"
    writeFile "node_modules/typescript/lib/typescript.d.ts" "src/bin/typescript.fs"
    // writeFile "node_modules/@types/electron/index.d.ts" "src/bin/electron.fs"
    // writeFile "node_modules/@types/react/index.d.ts" "src/bin/react.fs"
    // writeFile "node_modules/@types/node/index.d.ts" "src/bin/node.fs"
```

I am on vacation for an extended weekend. I'll be back next week.

**Comment by ctaggart** [comment]
On issue that someone may wish to jump on is to make a function like `createEnumName`. Electron currently ends up with this invalid F# enum names. Enum names must start with a letter and not contain dashes.

``` fs
    type [<StringEnum>] [<RequireQualifiedAccess>] SystemColor =
        | 3d-dark-shadow
        | 3d-face
        | 3d-highlight
        | 3d-light
        | 3d-shadow
        | [<CompiledName "active-border">] Active-border
        | [<CompiledName "active-caption">] Active-caption
        | [<CompiledName "active-caption-gradient">] Active-caption-gradient
```

**Comment by ctaggart** [comment]
@alfonsogarciacaro It may be good to merge this into `develop` branch and then we can pick up the remaining issues separately.

**Comment by kunjee17** [comment]
If possible we can push it to NPM. So, community can file more issue after using it. I am very much sure that many people are waiting for this. Again thanks @ctaggart for your work. :)

**Comment by ctaggart** [comment]
It isn't ready for npm yet. I'd like to have it work for those test projects first and not be on vacation when it is. :-)

**Comment by Zaid-Ajaj** [comment]
@ctaggart about `createEnumName`, the following should give a head start :smile:, you might want to tweek how you handle digits in the beginning, right now I just appended "N" when the enum begins with digit

```fsharp
let (|Capital|_|) (letter: string)= 
    let capitals = [ 'A' .. 'Z' ] |> Seq.map string
    match Seq.contains letter capitals with
    | true -> Some letter
    | false -> None

let (|Digit|_|) (digit: string) = 
    let capitals = [ '0' .. '9' ] |> Seq.map string
    match Seq.contains digit capitals with
    | true -> Some digit
    | false -> None

let createEnumNameParts (name: string) = 
    let tokens = Seq.map string name
    let rec splitParts part parts  = 
        function
        | [] -> part :: parts
        | Digit n :: rest when 
            // Append N to beginning only if enum starts with digit
            List.isEmpty parts
         && part = "" -> splitParts ("N" + n) parts rest 
        | Capital letter :: rest when part = "" -> splitParts letter parts rest
        | Capital letter :: rest -> splitParts letter (part :: parts) rest
        | "-" :: rest -> splitParts "" (part :: parts) rest
        | token :: rest ->  splitParts (part + token) parts rest
    tokens 
    |> List.ofSeq
    |> splitParts "" []  
    |> List.rev

createEnumNameParts "simpleCase" // ["simple"; "Case"]
createEnumNameParts "simple-kebab-case" // ["simple"; "kebab"; "case"]
createEnumNameParts "Other-Cases" // ["Other"; "Cases"]
createEnumNameParts "helloThereItsMe" // ["hello"; "There"; "Its"; "Me"]
createEnumNameParts "OtherSimpleCase" // ["Other";"Simple"; "Case"]
createEnumNameParts "2d-shadow" // ["N2d"; "shadow"]
createEnumNameParts "shadow-2d" // ["shadow"; "2d"]
createEnumNameParts "shadow-2d-more" // ["shadow"; "2d"; "more"]

let capitalize (input: string): string =
    if String.IsNullOrWhiteSpace input then ""
    else sprintf "%c%s" (Char.ToUpper input.[0]) (input.Substring 1)

let createEnumName = List.map capitalize >> String.concat ""
```

the function `createEnumNameParts` could be optimized a bit to use chars (I convert everything to strings)

**Comment by alfonsogarciacaro** [comment]
Awesome @ctaggart! Thanks a lot for all your work and enjoy your vacation! 😎

**Comment by ctaggart** [comment]
I'm back from vacation. Riding camels in the Sahara was fun. I've created separate issues for all todos that were not complete.

**Comment by mike-morr** [comment]
@ctaggart I tried it with @types/sharepoint and ended up with a few errors in the file after.

image

and

image

There are also a lot of ```The type X is undefined```

**Comment by ctaggart** [comment]
Thanks @mike-morr. Can you create a new issue and show what you are getting as well as what you expect it should output in order to work?

**Pull request merged**
