### PR TITLE
Adding missing imports

### PR DESCRIPTION
**Pull request by realvictorprm**
This import is needed too.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Hmm, Node libraries won't use the browser API and now we're a moving the Browser bindings out of Fable.Core. Not sure how to fix this... maybe add an option so ts2fable knows if it's a browser or node library?

**Comment by realvictorprm** [comment]
Good idea...
Well I'm not that conform with Type Script yet. Also the structure here is a bit confusing for me.

**Comment by alfonsogarciacaro** [comment]
Yeah, ts2fable is a bit of spaguetti code at the moment, we need to fix that 😕

**Comment by ctaggart** [comment]
This pull request should be closed. We can address this is part of https://github.com/fable-compiler/ts2fable/issues/26 instead.

**Comment by alfonsogarciacaro** [comment]
Good point, thanks @ctaggart!

**Pull request closed without merging**
