### PR TITLE
WIP Try to add multi links support

### PR DESCRIPTION
**Pull request by humhei**
@ctaggart I want to import reactxp@0.46.5 to fable
Here are some commits 
Feel free to modify it 😄

### CODE REVIEW

**Comment by humhei** [comment]
I would investigate more to make sure the correctness of code

**Comment by ctaggart** [comment]
Thanks for the work here. I may have some time at the end of the week to review.

**Comment by humhei** [comment]
@alfonsogarciacaro @ctaggart 
Thank you for your kind
I am really a new one of F# world , git world and english world
👍 
If i  taked some mistakes , please figure it out 
❤️

**Comment by humhei** [comment]
I try to convert all the TS Files to its  corresponding FS Files
Today i find that the TS Files are referenced each other which can not be done in f#
So currently I try to bundle them togother

**Comment by humhei** [comment]
Close this PR 
Progressively contribute to this reposity
I am still working on my reposity for this goal

**Comment by ctaggart** [comment]
@humhei We really do appreciate your contributions. Some new contracts and other priorities have prevented me from contributing this last month here, but I'll be back to review when other things settle down.

**Pull request closed without merging**
