### PR TITLE
import @param documentation comments

### PR DESCRIPTION
**Pull request by ctaggart**
fix fable-compiler/ts2fable#89

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I would prefer to use this kind of comments for the documentation:

```
///**Description**
///
///**Parameters**
///  * `url` - parameter of type `string`
///
///**Output Type**
///  * `string`
///
///**Exceptions**
///
let private bundleScriptTag url = sprintf "<script src=\"%s\"></script>\n</body>" url
```

This is generated by Ionide and understand by F# Formatting. This would allow us to generate documentation more easily if we want etc.

**Comment by ctaggart** [comment]
@MangelMaxime Can do. Do you have a link to the spec?

**Comment by MangelMaxime** [comment]
Perhaps @Krzysztof-Cieslak know where we can find it ?

But Ionide, generate all the time the same structure for the doc comments.

1. A description
2. A list of parameters
3. And the ouput type as a single list element
4. A list of exception, with explanation when needed

Examples:

```fs
///**Description**
///
///**Parameters**
///  * `x` - parameter of type `int`
///  * `y` - parameter of type `int`
///  * `z` - parameter of type `int`
///
///**Output Type**
///  * `int`
///
///**Exceptions**
///
let add x y z = x + y + z

///**Description**
///
///**Parameters**
///  * `y` - parameter of type `int`
///  * `z` - parameter of type `int`
///
///**Output Type**
///  * `int`
///
///**Exceptions**
///
let add2 y z = add 1 y z
```

**Comment by ctaggart** [comment]
I opened up https://github.com/fable-compiler/ts2fable/issues/131 for the proposal. Merging this now that it is working.

**Pull request merged**
