### PR TITLE
Add monaco-editor to auto generated files

### PR DESCRIPTION
**Pull request by MangelMaxime**
In Fable repl, and another project I am working on for Fable eco-system I need to use Monaco.

I think it's a good thing to add it's bindings to the project. Please tell, if I missed something :)

### CODE REVIEW

**Comment by humhei** [comment]
https://github.com/fable-compiler/ts2fable-exports/blob/dev/Monaco.fs

**Comment by MangelMaxime** [comment]
Thank you :)

**Comment by humhei** [comment]
I am a bit busy these days.
I hope more people can join this repository.
Add their package and help to contribute this repository.

**Comment by MangelMaxime** [comment]
I understand your point and perhaps one day this will be possible :)

I am here since the beginning of Fable and we have always been a small team of people. But community is really helpful in general and contribute when they have time :)

**Pull request merged**
