### PR TITLE
remove private members from classes

### PR DESCRIPTION
**Pull request by 0x53A**
The reason for this PR is that babylonJs has many private members in their .d.ts:

```
Find all "private", Match case, Whole word, Find Results 1, Current Document
  Matching lines: 2592
```

I wasn't able to test it at all, because the build fails for me locally

grafik

### CODE REVIEW

**Comment by 0x53A** [comment]
Hm, ``git clean -f -d -x`` got rid of that error, but now I get a 404 from yarn:

grafik

The exact url is https://github.com/sass/node-sass/releases/download/v4.9.2/win32-x64-67_binding.node

and it looks like that file wasn't released:

grafik

Just up to 64, no 67

**Comment by 0x53A** [comment]
So from my side this looks good.

Rerunning it on babylonjs, the lines changed from 31385 to 28659, so 2k7 lines removed.

---

Open question:

does anyone rely on private members being accessible? There is no private in JS, so they any access would have worked.

Should I add a configuration that defaults to keep privates?

**Comment by StachuDotNet** [comment]
"Should I add a configuration that defaults to keep privates?"
For those rare edge cases where you need to access private members, I think it'd be best to add such a configuration object - or - provide documentation of how to otherwise get around such exclusions.

**Comment by 0x53A** [comment]
The workaround would be to dynamically access the member:

assuming ``o`` has a private field ``_myPrivateField`` of type string:

```fs
open Fable.Core.JsInterop

let f : string = !! o?_myPrivateField
```

**Comment by StachuDotNet** [comment]
That's not too bad.

**Comment by humhei** [comment]
@0x53A  
Thanks very much for your work

Is it necessary to add a test when your making a repair 😕 (Please tell me what you think)
https://github.com/fable-compiler/ts2fable/pull/231/files

When i develop ts2fable, add a fsfile test will always make my work much easily,
As it only tracks part AST but not all AST.

Also , tests may make ts2fable more robust

**Comment by humhei** [comment]
BTW, 
Just to prevent you don't know
You can also see all the changes in ts2fable-exports https://github.com/fable-compiler/ts2fable-exports/commit/52cfeac17cc68e34aba48a5b94a27669ecf7785c

**Comment by humhei** [comment]
https://github.com/fable-compiler/ts2fable-exports/commit/7db9934a666c3ef40170595287260d5dcb1343bb#diff-56d270b91244984b41bd03fdd37d3117R677

This PR removed private contructor 
But aslo add a useless contructor

Please check it @0x53A

**Comment by humhei** [comment]
@alfonsogarciacaro  
Add @0x53A  as a member of ts2fable?

**Comment by 0x53A** [comment]
@humhei thank you for pointing me to it, ts2fable-exports is really usefull.

That ctor issue may be fixed by reordering it so that privates are removed after ctors are autogenerated, but that feels a bit like programming by accident, so I'll take another look.

**Comment by humhei** [comment]
Please tell me When you are ready. I will merge it and draft a new release

**Comment by 0x53A** [comment]
I was just reviewing the latest diff (https://github.com/fable-compiler/ts2fable-exports/commit/4f589d4#diff-b12380b) and it looks good from my side.

I think reordering is the correct thing to do.

Only thing missing is tests for this and my two other PRs 😅

**Comment by 0x53A** [comment]
And I'd like to add babylonjs into CI, if possible.

It does not yet compile out-of-box, there still a small number of manual corrections required, but I'd like to get it so far that it will compile out-of-box.

**Comment by humhei** [comment]
image
You can add it in here

**Comment by humhei** [comment]
@0x53A 
Due to the time differences
I cannot merge your pull requests in time

**1.** You can ask @MangelMaxime to merge it. 
**2.** Wait for me lately.
**3.** Ask @alfonsogarciacaro give your the rights, So you can merge it yourself

The only thing you should  pay attention to is #283

**Comment by 0x53A** [comment]
@humhei thank you! Option 2) is perfectly fine for me.

I don't have the historical context for #283, but in the short time I've worked on this codebase it wasn't any issue.

Rather the reverse, the simplicity (just a few chained functions) makes it really easy to grok what is going on.

**Pull request merged**
