### PR TITLE
Feature/online

### PR DESCRIPTION
**Pull request by MangelMaxime**
Prepare for: #233 

I create a [placeholder function](https://github.com/fable-compiler/ts2fable/compare/feature/online?expand=1#diff-285d98849830dbc5ffb4f9ac09cc9d37R24)

In the future it will need to be replace by an actual call on ts2fable.

I also, update the `build.fsx` a bit because it wasn't able to run the `dotnet` commands for the web-app. It was failing with a .net error.

### CODE REVIEW

**Comment by humhei** [comment]
@MangelMaxime  feel free to merge it yourself when you are ready
Thanks very much for your work ❤️

**Comment by MangelMaxime** [comment]
@humhei For me it's ready to be merge. I don't know why the tests are failing.

I didn't touch the code from ts2fable. Will you be able to fix it after ? Or do you want to fix it in this PR ?

**Comment by humhei** [comment]
Don't worry,i will fix it

**Comment by MangelMaxime** [comment]
@humhei Thank you :)

**Pull request merged**
